inherit_from: ../.rubocop.yml

AllCops:
  Exclude:
    - 'bin/*'

  TargetRubyVersion: 2.4

Layout/LineLength:
  Exclude:
    - 'spec/*'

# rspec blocks are huge by design
Metrics/BlockLength:
  Exclude:
    - 'spec/*'