inherit_from: ../.rubocop.yml

#
# This file contains temporary ignore statements to shut down warnings 
# about stuff that is already scheduled for refactoring. 
#

#Metrics/AbcSize:
#  Enabled: false

#Metrics/CyclomaticComplexity:
#  Enabled: false

#Metrics/LineLength:
#  IgnoredPatterns: ['^\s+return {errors: \[', '\A\s*#', '\A\s*Then\(']

#Metrics/MethodLength: 
#  Enabled: false

#Metrics/BlockLength:
#  Enabled: false

#Metrics/ModuleLength:
#  Enabled: false

#Metrics/ClassLength:
#  Enabled: false

#Metrics/PerceivedComplexity:
#  Enabled: false

#Style/Documentation:
#  Enabled: false
