inherit_from: ../.rubocop.yml

AllCops:
  Exclude:
    - 'bin/*'

  TargetRubyVersion: 2.4

Layout/LineLength:
  Exclude:
    - 'spec/**/*.rb'

# setting to 6 to match RubyMine autoformat
Layout/FirstArrayElementIndentation:
  IndentationWidth: 6


# rspec blocks are huge by design
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

